import django_tables2 as tables
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django_filters.views import FilterView

from .filters import TicketFilter
from .forms import TicketAttachmentForm, TicketCommentForm, TicketForm
from .models import Reference, Ticket, TicketAttachment
from .tables import TicketTable


class AllTickets(LoginRequiredMixin, tables.SingleTableMixin, FilterView):
    model = Ticket
    table_class = TicketTable
    filterset_class = TicketFilter
    template_name = "tickets/all-user-tickets.html"
    paginate_by = 20

    def get_queryset(self, **kwargs):
        # Override queryset method to filter tickets by authenticated user.
        qs = super().get_queryset(**kwargs)
        self.filterset = TicketFilter(data=self.request.GET, queryset=qs.order_by("-created_at"), request=self.request)
        return self.filterset.qs

    def get_template_names(self):
        if self.request.htmx:
            template_name = "tickets/table/ticket-table-partial.html"
        else:
            template_name = "tickets/all-user-tickets.html"

        return template_name

    def get_context_data(self, **kwargs):
        # Add form generated by filterset to the context
        context = super().get_context_data(**kwargs)
        context["filter_form"] = self.filterset.form
        context["page"] = "all-tickets"
        return context


@login_required
def ticket_details(request, ticket_number):
    selected_ticket = get_object_or_404(Ticket, ticket_number=ticket_number)
    ticket_comments = selected_ticket.comments.all().order_by("-created_at")
    ticket_file_count = selected_ticket.attachments.all().count()

    comment_form = TicketCommentForm()
    attachment_form = TicketAttachmentForm(new_ticket=False)
    ticket_form = TicketForm(instance=selected_ticket)
    if request.method == "POST":

        # Only ticket author and assigned agent are allowed to comment on ticket
        if (
            "add-comment" in request.POST
            and request.user == selected_ticket.created_by
            or request.user == selected_ticket.assigned_agent
        ):
            comment_form = TicketCommentForm(data=request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.created_by = request.user
                comment.ticket = selected_ticket
                comment.save()
                messages.success(request=request, message="Your comment was posted successfully.")
                return redirect(to="ticket-details", ticket_number=ticket_number)
            else:
                messages.error(request=request, message="You did not enter any comment.")
        # Only ticket author is allowed to edit ticket and add attachment
        elif "add-attachment" in request.POST and request.user == selected_ticket.created_by:
            attachment_form = TicketAttachmentForm(
                data=request.POST, files=request.FILES, file_count=ticket_file_count, new_ticket=False
            )
            if attachment_form.is_valid():
                files = attachment_form.cleaned_data.get("attachment")
                create_attachment(files=files, ticket=selected_ticket)
                messages.success(request=request, message="Attachment has been added successfully.")
                return redirect(to="ticket-details", ticket_number=ticket_number)
            else:
                # https://docs.djangoproject.com/en/5.0/ref/forms/api/#django.forms.ErrorList.as_text
                error = attachment_form.errors.get("attachment").as_text().replace("*", "")
                messages.error(request=request, message=error)
        elif "edit-ticket" in request.POST and request.user == selected_ticket.created_by:
            ticket_form = TicketForm(instance=selected_ticket, data=request.POST)
            if ticket_form.is_valid():
                selected_ticket._change_reason = "Ticket details have been updated."
                ticket_form.save()
                messages.success(request=request, message="Change saved successfully.")
            else:
                messages.error(
                    request=request,
                    message="Failed to update ticket details. Please make sure to answer all required fields.",
                )
        else:
            messages.error(request=request, message="You are not authorized to perform this action.")

    context = {
        "selected_ticket": selected_ticket,
        "comment_form": comment_form,
        "attachment_form": attachment_form,
        "ticket_form": ticket_form,
        "ticket_comments": ticket_comments,
        "page": "ticket",
    }
    return render(request=request, template_name="tickets/ticket-detail.html", context=context)


def create_attachment(files, ticket):
    """This function accepts a list of Files object and creates attachment
    records in the database

    Args:
        files (list): List of file objects
        ticket (_type_): Ticket object that will be related to the attachment
    """

    obj = []
    for file in files:
        obj.append(TicketAttachment(attachment=file, ticket=ticket))

    TicketAttachment.objects.bulk_create(obj)
    ticket._change_reason = "File attachment was added to the ticket."
    ticket.save()


@login_required
def create_ticket(request):
    if request.method == "POST":
        ticket_form = TicketForm(data=request.POST, files=request.FILES)
        attachment_form = TicketAttachmentForm(data=request.POST, files=request.FILES, file_count=0, new_ticket=True)
        if ticket_form.is_valid() and attachment_form.is_valid():
            ticket = ticket_form.save(commit=False)
            ticket.created_by = request.user
            ticket.ticket_number = Reference.generate(prefix="INC")
            ticket._change_reason = "Ticket has been created."
            ticket.save()

            files = attachment_form.cleaned_data["attachment"]
            if files:
                create_attachment(files=files, ticket=ticket)
            messages.success(
                request=request,
                message=(
                    f"Your ticket {ticket.ticket_number} has been created. Our support team will get back to you as"
                    " soon as possible, we appreciate your patience. If you have any additional information or"
                    " questions, feel free to add them to the ticket. "
                ),
            )
            return redirect(to="ticket-details", ticket_number=ticket.ticket_number)
    else:
        ticket_form = TicketForm()
        attachment_form = TicketAttachmentForm(file_count=0, new_ticket=True)

    context = {
        "ticket_form": ticket_form,
        "attachment_form": attachment_form,
        "page": "new-ticket",
    }
    return render(request=request, template_name="tickets/create-ticket.html", context=context)


@login_required
def delete_attachment(request, ticket_number, pk):
    attachment = get_object_or_404(TicketAttachment, id=pk)

    if request.user == attachment.ticket.created_by:
        attachment.delete()
        messages.success(request=request, message="Attachment has been deleted successfully.")
    else:
        messages.error(request=request, message="You are not authorized to perform this action.")
    return redirect(to="ticket-details", ticket_number=ticket_number)


@login_required
def assign_ticket(request, ticket_number):
    selected_ticket = get_object_or_404(Ticket, ticket_number=ticket_number)
    if selected_ticket.created_by == request.user:
        messages.error(
            request=request,
            message="You're not allowed to accept a ticket you've created.",
        )
    elif ("accept" in request.POST and not selected_ticket.assigned_agent) and (
        request.user.role == 1 or request.user.role == 2
    ):
        selected_ticket.assign_agent(user=request.user)
        selected_ticket.set_status_assigned()
        selected_ticket.save()
        messages.success(
            request=request,
            message="You've successfully accepted this ticket. Click on Start Work to start the ticket progress.",
        )
    else:
        messages.error(
            request=request,
            message="You are either not authorized to accept this ticket, or this ticket is already assigned.",
        )
    return redirect(to="ticket-details", ticket_number=ticket_number)


@login_required
def update_ticket_status(request, ticket_number):
    selected_ticket = get_object_or_404(Ticket, ticket_number=ticket_number)
    actions = {
        "start": {
            "allowed_users": [1, 2],
            "update_status": selected_ticket.set_status_in_progress,
            "message": "This ticket is now In Progress.",
        },
        "close": {
            "allowed_users": [1, 2, 3],
            "update_status": selected_ticket.set_status_close,
            "message": "This ticket is now Closed.",
            "comment": "Closed the ticket",
        },
        "resolve": {
            "allowed_users": [1, 2],
            "update_status": selected_ticket.set_status_resolved,
            "message": "This ticket is now resolved.",
            "comment": "Resolved the ticket",
        },
        "hold": {
            "allowed_users": [1, 2],
            "update_status": selected_ticket.set_status_on_hold,
            "message": "This ticket is now on hold status.",
            "comment": "Placed the ticket on hold",
        },
        "resume": {
            "allowed_users": [1, 2],
            "update_status": selected_ticket.set_status_in_progress,
            "message": "This ticket is now In Progress.",
        },
        "reopen": {
            "allowed_users": [1, 2, 3],
            "update_status": selected_ticket.set_status_open,
            "message": (
                f"Ticket has been reopened and reassigned to {selected_ticket.assigned_agent}"
                if selected_ticket.assigned_agent
                else "This ticket has been opened."
            ),
            "comment": "Reopened the ticket",
        },
    }

    for key in actions:
        if (key in request.POST and request.user.role in actions[key]["allowed_users"]) and (
            request.user == selected_ticket.assigned_agent or request.user == selected_ticket.created_by
        ):
            comment_form = TicketCommentForm(data=request.POST)
            if key == "start" or key == "resume":
                actions[key]["update_status"]()
                selected_ticket.save()
                messages.success(request=request, message=actions[key]["message"])
            elif comment_form.is_valid():
                actions[key]["update_status"]()
                selected_ticket.save()

                comment = comment_form.save(commit=False)
                comment.comment = actions[key]["comment"] + " - " + comment.comment
                comment.created_by = request.user
                comment.ticket = selected_ticket
                comment.save()
                messages.success(request=request, message=actions[key]["message"])
            else:
                messages.error(request=request, message="Please enter the reason for updating the ticket status.")
            return redirect(to="ticket-details", ticket_number=ticket_number)

    messages.error(request=request, message="You are not authorized to perform this action.")
    return redirect(to="ticket-details", ticket_number=ticket_number)
