# Generated by Django 4.2.7 on 2023-11-30 08:36

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=False, null=True, quality=-1, scale=None, size=[300, 300], upload_to='images'),
        ),
    ]
