# Generated by Django 5.0.1 on 2024-02-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_role_delete_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Administrator'), (2, 'Support Agent'), (3, 'Customer')], default=3),
        ),
    ]
