# Generated by Django 5.0.1 on 2024-02-29 14:40

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, choices_display='WITH_GMT_OFFSET', null=True, use_pytz=False),
        ),
    ]
