# Generated by Django 4.2.7 on 2023-11-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_assigned_agent_ticket_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketstatus',
            options={'verbose_name_plural': 'Ticket Status'},
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='type',
            field=models.IntegerField(choices=[(1, 'Service Request'), (2, 'Incident'), (3, 'Problem'), (4, 'Change Request')]),
        ),
    ]
