# Generated by Django 4.2.7 on 2023-11-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticketstatus_options_alter_tickettype_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketpriority',
            options={'verbose_name_plural': 'Ticket Priorities'},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_summary',
            new_name='summary',
        ),
    ]
