# Generated by Django 4.2.7 on 2023-12-18 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_ticket_assigned_agent_alter_ticket_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='comments',
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='tickets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='tickets.ticket'),
        ),
    ]
