# Generated by Django 4.2.7 on 2023-12-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_remove_ticket_comments_ticketcomment_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments'),
        ),
    ]
