# Generated by Django 4.2.7 on 2023-12-23 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0012_ticket_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketcomment',
            old_name='tickets',
            new_name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='tickets.ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
