# Generated by Django 4.2.7 on 2024-01-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_remove_ticket_priority_id_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issue_type',
            field=models.IntegerField(choices=[(1, 'Service Request'), (2, 'Incident'), (3, 'Problem'), (4, 'Change Request')], default=1),
        ),
    ]
