# Generated by Django 5.0.1 on 2024-01-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_alter_ticket_issue_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketPriority',
        ),
        migrations.DeleteModel(
            name='TicketStatus',
        ),
        migrations.DeleteModel(
            name='TicketType',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issue_type',
            field=models.IntegerField(choices=[(1, 'Service Request'), (2, 'Incident'), (3, 'Problem'), (4, 'Change Request')]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='summary',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
