# Generated by Django 5.0.1 on 2024-03-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_historicalticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketActivity',
        ),
    ]
